### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by DrLeturc** [HyperAgents/hmas#17]
In the core ontology, comments are missing. I added some of them. Here is a proposal : 

:contains a owl:ObjectProperty ;
          owl:inverseOf :isContainedBy ;
          rdfs:domain :Workspace ;
          rdfs:comment "A relation which describes the resources contained in a workspace "@en ;
          rdfs:label "contains"@en .

:containsAgent a owl:ObjectProperty ;
               rdfs:subPropertyOf :contains ;
               rdfs:domain :Workspace ;
               rdfs:range :Agent ;
               rdfs:comment "A relation which agents are contained in a workspace "@en ;
               rdfs:label "contains agent"@en .

:containsArtifact a owl:ObjectProperty ;
                  rdfs:subPropertyOf :contains ;
                  rdfs:domain :Workspace ;
                  rdfs:range :Artifact ;
                  rdfs:comment "A relation which describes the artifacts contained in a workspace "@en ;
                  rdfs:label "contains artifact"@en .

:describes a owl:ObjectProperty ;
           owl:inverseOf :isDescribedBy ;
           rdfs:domain [ a owl:Class ;
                         owl:unionOf ( :ResourceProfile
                                       :Signifier
                                     )
                       ] ;
           rdfs:comment "A relation which describes  all signifiers associated to a resource profile"@en ;
           rdfs:label "describes"@en .

:hasHomePlatform a owl:ObjectProperty ;
                 rdfs:subPropertyOf :isHostedBy ;
                 owl:inverseOf :hostsAgent ;
                 rdfs:domain :Agent ;
                 rdfs:range :Platform ;
                 rdfs:comment "A relation which describes the home platforms for an agent"@en ;
                 rdfs:label "has home platform"@en .

What is the difference the main difference with the property :hosts ? Do we need it ? 

:hasHomeWorkspace a owl:ObjectProperty ;
                  rdfs:subPropertyOf :isContainedBy ;
                  owl:inverseOf :isHomeOf ;
                  rdfs:comment "A relation which describes if a workspace is a home workspace for an agent "@en ;
                  rdfs:label "has home workspace"@en .

:hasSignifier a owl:ObjectProperty ;
              rdfs:domain :ResourceProfile ;
              rdfs:range :Signifier ;
              rdfs:label "has signifier"@en ;
              rdfs:comment "A relation between a resource profile and a signifier describing the affordances of the resource"@en .

:hosts a owl:AsymmetricProperty ;
       owl:inverseOf :isHostedBy ;
       rdfs:domain :Platform ;
       rdfs:comment "A relation which describes the resources hosted by a platform"@en ;
       rdfs:label "hosts"@en .

:hostsAgent a owl:ObjectProperty ;
            rdfs:subPropertyOf :hosts ;
            rdfs:domain :Platform ;
            rdfs:range :Agent ;
            rdfs:comment "A relation which describes the agents hosted by a platform"@en ;
            rdfs:label "hosts agent"@en .

:hostsWorkspace a owl:ObjectProperty ;
                rdfs:subPropertyOf :hosts ;
                rdfs:domain :Platform ;
                rdfs:range :Workspace ;
                rdfs:comment "A relation which describes the workspaces hosted by a platform"@en ;
                rdfs:label "hosts workspace"@en .

:isContainedBy a owl:ObjectProperty ;
               rdfs:subPropertyOf owl:topObjectProperty ;
               rdfs:range :Workspace ;
               rdfs:comment "A relation which describes the resources contained in a workspace"@en ;
               rdfs:label "is contained by"@en .

:isDescribedBy a owl:AsymmetricProperty ;
               rdfs:range [ a owl:Class ;
                            owl:unionOf ( :ResourceProfile
                                          :Signifier
                                        )
                          ] ;
               rdfs:comment "A relation which maps the resource profiles and signifiers associated to a resource"@en ;
               rdfs:label "is described by"@en .

:isHomeOf a owl:AsymmetricProperty ;
          rdfs:subPropertyOf :containsAgent ;
          rdfs:domain :Workspace ;
          rdfs:range :Agent ;
          rdfs:comment "A relation which describes if a workspace is a home workspace for an agent"@en ;
          rdfs:label "is home of"@en .

:isHostedBy a owl:AsymmetricProperty ;
            rdfs:range :Platform ;
            rdfs:comment "A relation which describes what are the resources hosted by a platform"@en ;
            rdfs:label "is hosted by"@en .

**Comment by aeoess** [comment]
@tomjwxf — the receipt-signed mutation log is the right architecture for self-improving systems. The conflict of interest you identified — a meta-agent evaluating its own modifications — is structurally identical to the self-attestation problem in agent governance.

Our approach to the same problem: the 3-signature chain separates intent (agent signs), evaluation (policy engine signs), and execution (gateway signs). The agent can't forge receipts for actions it didn't take because the gateway is an independent signer. For the HyperAgents generate-evaluate loop, the equivalent would be: meta-agent signs the proposed modification, an independent evaluator signs the test result, and the deployment system signs the actual code swap. Three independent signers, none of which can forge the others' receipts.

The receipt chain you described (iteration hash → signed → chains to previous) is exactly how our `ReceiptLedger` works — append-only, Merkle-committed, with inclusion proofs per receipt. A third party can verify any individual iteration was part of the committed history without seeing the full chain. Selective disclosure for code evolution.

One addition worth considering: `ExecutionAttestation` with parameter drift detection. After each iteration, compare the meta-agent's declared improvement metric against the actual test results. Field-level divergence classification (benign/suspicious/critical) catches cases where the meta-agent claims improvement but the tests show regression — signed and tamper-evident.

The 3-layer architecture we endorsed earlier (APS identity + protect-mcp execution policy + receipt chain evidence) maps directly to this use case. APS provides the meta-agent's identity and delegation scope. protect-mcp constrains what modifications are allowed. The receipt chain proves what actually happened.
