### ISSUE TITLE
A question about fipa:AgentDescription

### ISSUE THREAD

**Issue by YoucTagh** [HyperAgents/hmas#174]
In [core.ttl](https://github.com/HyperAgents/hmas/blob/master/src/core.ttl#L233), `:ResourceProfile` mentions `fipa:AgentDescription` as an example. However, there is no such class in [fipa.ttl](https://github.com/HyperAgents/hmas/blob/master/src/fipa.ttl).

Also, the prefix `fipa` is used in that `skos:example` when it is not defined with the prefixes. Meanwhile, there are other prefixes that are defined but not used: `voaf` and `foaf`.

**Comment by FabienGandon** [comment]
For FIPA: as the mention of `fipa:AgentDescription` is inside a literal there is no syntactic problem but one could replace that qname with an expression like "an agent description based on the FIPA standard"

The `foaf` prefix could be removed indeed since we moved to `schema`.

The [`voaf`](https://lov.linkeddata.es/vocommons/voaf/v2.3/) prefix could be kept if we intend to use any of these for instance: `voaf:Vocabulary`, `voaf:classNumber`, `voaf:propertyNumber`

**Comment by danaivach** [comment]
@andreiciortea, Fabien's proposal appears to address the issue, but I'm reaching out to you because the topic is related to the FIPA OWL ontology that you have contributed.

**Comment by smnmyr** [comment]
..and there is no initiative to add AgentDescription to the fipa.ttl? It would fit there...

**Comment by andreiciortea** [comment]
+1 for @FabienGandon's proposal, it is more descriptive and clear

@smnmyr we'll need to update the FIPA vocabulary. For that one, we did not follow a specific methodology. I will bring this up in today's heartbeat meeting.

**Comment by FabienGandon** [comment]
this issue is now covered in PR #186
